name: Task 1 - Clone and Push Check
permissions:
  issues: write
on:
  push:
    paths:
      - 'setup-done.txt'

jobs:
  check-clone:
    runs-on: ubuntu-latest
    steps:
      - name: Celebrate successful clone and push
        run: echo "✅ Task 1 Complete:You cloned the repo and pushed a file!"

      - name: Find or create issue
        id: issue
        uses: actions/github-script@v6
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            let issue = issues.find(issue => issue.title.includes('Task 1: Clone and Push'));
            if (!issue) {
              const { data: newIssue } = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Task 1: Clone and Push',
                body: 'This issue tracks the completion of Task 1.'
              });
              issue = newIssue;
            }
            core.setOutput('issue-number', issue.number);

      - name: Comment on issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.issue.outputs.issue-number }},
              body: '✅ **Task 1 Complete**: You cloned the repo and pushed a file!'
            });
