name: Task 1 - Clone and Push Check
on:
  push:
    paths:
      - 'setup-done.txt'

jobs:
  check-clone:
    runs-on: ubuntu-latest
    steps:
      - name: Celebrate successful clone and push
        run: echo "✅ Task 1 Complete:You cloned the repo and pushed a file!"
